const VERIFY_PROPERTY = 'VERIFY_PROPERTY';
const SET_PROPERTY = 'SET_PROPERTY';
const PROPERTY_CHAT_CONNECTED = 'PROPERTY_CHAT_CONNECTED';
const PROPERTY_CONNECTED = 'PROPERTY_CONNECTED';
const USER_CONNECTED = 'USER_CONNECTED';
const USER_DISCONNECTED = 'USER_DISCONNECTED';
const USER_LOGOUT = 'USER_LOGOUT';
const PROPERTY_LOGOUT = 'PROPERTY_LOGOUT';
const CHAT_REQUEST = 'CHAT_REQUEST';
const NEW_CHAT = 'NEW_CHAT';
const INIT_SOCKET = 'INIT_SOCKET';
const MESSAGE_DELIVERED = 'MESSAGE_DELIVERED';
const MESSAGE_PROPERTY = 'MESSAGE_PROPERTY';
const MESSAGE_SENT = 'MESSAGE_SENT';
const PROPERTY_MESSAGE_SENT = 'PROPERTY_MESSAGE_SENT';

const PROPERTY_DISCONNECTED = 'PROPERTY_DISCONNECTED';
const SERVER_ERROR = 'serverError';

module.exports = {
    VERIFY_PROPERTY,
    SET_PROPERTY,
    PROPERTY_CONNECTED,
    PROPERTY_LOGOUT,
    SERVER_ERROR,
    MESSAGE_DELIVERED,
    MESSAGE_SENT,
    MESSAGE_PROPERTY,
    CHAT_REQUEST,
    NEW_CHAT,
    USER_CONNECTED,
    USER_LOGOUT,
    PROPERTY_CHAT_CONNECTED,
    PROPERTY_MESSAGE_SENT
};